2021.2.0 Release -internal update: Fix java.lang.NoClassDefFoundError: com/intellij/util/exception/FrequentErrorLogger error for WebStorm 2021.2;         <br>- remove 1 usage of scheduled for removal API         <pre>React Native Console Free 2020.2 uses API scheduled for removal in future releases         Scheduled for removal constructor usage (1)         NotificationGroup.<init>(...) (1) (scheduled for removal in 2021.3)             Deprecated constructor NotificationGroup.<init>(...) is invoked in CleanSourceCommentAction.process(...).                 This constructor will be removed in 2021.3</pre>